name: CD Pipeline2

on:
  workflow_run:
    workflows: ["CD Pipeline"]
    types:
      - completed
jobs:

  build:

    runs-on: webserver2

    steps:
    - name: Log in to Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Pull Docker image
      run: docker pull dokinik/mchosting-cicd:latest
    - name: Delete Old docker container
      run: docker rm -f mchosting-cicd2 || true
    - name: Run Docker Container
      run: docker run -d -p 80:80 --name mchosting-cicd2 dokinik/mchosting-cicd